name: fixnow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  go_router: ^14.4.1
  formz: ^0.8.0
  google_nav_bar: ^5.0.7
  flutter_dotenv: ^5.2.1
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  table_calendar: ^3.1.2
  intl: ^0.19.0
  fl_chart: ^0.69.1
  firebase_messaging: ^15.1.5
  firebase_core: ^3.8.0
  percent_indicator: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/facebook.png
    - assets/images/carpinteria.png
    - assets/images/electricidad.png
    - assets/images/plomeria.png
    - assets/images/carpinteria2.jpg

    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf